# Configur/ction for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
# TERM variable
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
#TERM: xterm-256color
# https://alacritty.org/config-alacritty.html

# 配色方案
import = [
  "~/.config/alacritty/Dracula.toml"
]

# 自动加载
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# "Full" | "None" | "Transparent" | "Buttonless"
# Borders and title bar.
# Neither borders nor title bar.
# Title bar, transparent background and title bar buttons.
# Title bar, transparent background and no title bar buttons.
decorations = "Full" 
dynamic_padding = false
opacity = 0.93
dynamic_title = true


[window.padding]
x = 10
y = 5

# 字体设置
[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[cursor]
# Values for `style`:
#   - ▇ Block
#   - _ Underline
#   - | Beam
style="Block"

[selection]
semantic_escape_chars=",│`|:\"' ()[]{}<>"
# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard=true

[mouse]
# If this is `true`, the cursor is temporarily hidden when typing.
hide_when_typing=true